### ISSUE TITLE
Issue in docs when building KLEE

### ISSUE THREAD

**Issue by chadbrewbaker** [project-oak/rust-verification-tools#15]
Getting this error on cmake for KLEE:

```bash
-- Looking for bitcode compilers
CMake Error at cmake/find_bitcode_compiler.cmake:27 (message):
  Failed to find C bitcode compiler
Call Stack (most recent call first):
  CMakeLists.txt:292 (include)
# attempts to match "clang-${LLVM_VERSION_MAJOR}.${LLVM_VERSION_MINOR}" "clang" "llvm-gcc"
```
So KLEE needs clang as a dependency? Should the rust build also pull the corresponding clang to build?

Update. Seems Rust hosts a fork of llvm-project that includes clang: https://github.com/rust-lang/llvm-project

**Comment by alastairreid** [comment]
Yes, it needs clang and it really ought to be using clang from the llvm fork inside the Rust repo.
I don't see an obvious way to cause x.py to build clang.
In particular, I tried this (which takes a lot of time!)

```
export RUSTBUILD_FORCE_CLANG_BASED_TESTS=1
./x.py clean # try to force a rebuild
./x.py build
./x.py test   # run tests
```

I hoped that this would put clang in ~/rust/rust/build/x86*/llvm/bin but no luck.

So, I will amend the instructions to install clang explicitly and accept that this results in a mismatch.
(Also, may result in some warnings about mismatched configurations of some KLEE support files and the Rust code.)

**Comment by alastairreid** [comment]
(Change to install-klee.md pushed)
