### ISSUE TITLE
Crux backend

### ISSUE THREAD

**Issue by Shnatsel** [project-oak/rust-verification-tools#50]
Galois has just announced [Crux](https://crux.galois.com/), an open-source symbolic execution engine that operates on Rust MIR directly instead of LLVM IR. It might be worthwhile to use it instead of KLEE.

**Comment by alastairreid** [comment]
Hi Shnatsel,

Thanks for that - we appreciate the heads up.

We added [partial support for Crux](https://github.com/project-oak/rust-verification-tools/blob/main/docs/using-annotations.md#verifying-with-crux-mir) recently and we will look at whether the Galois packages are easier to use than the [instructions](https://github.com/project-oak/rust-verification-tools/blob/main/docs/install-crux.md) that we currently have.

Different tools tend to have different strengths that make them better/worse for different kinds of code so it is useful to be able to use a wide range of tools and to be able to switch from one tool to another with as little effort as possible.
So our goal for RVT is to support as many Rust verification tools as possible.
